some (hopefully) final touch ups

diff --git a/.github/workflows/nightly-build.yml b/.github/workflows/nightly-build.yml
--- a/.github/workflows/nightly-build.yml
+++ b/.github/workflows/nightly-build.yml
@@ -35,37 +35,26 @@ jobs:
     - name: Add MSBuild to PATH
       uses: microsoft/setup-msbuild@v1.0.2
 
-    - name: Build Latite
+    - name: Build Latite Nightly
       working-directory: ${{env.GITHUB_WORKSPACE}}
-      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
-      
-    - name: Get DLL SHA1 hash
-      id: sha1
-      working-directory: ${{ github.workspace }}/x64/Nightly
       run: |
-        function Get-GitStyleSha1 {
-          param ([string]$FilePath)
-          $fileContent = [System.IO.File]::ReadAllBytes($FilePath)
-          $fileSize = $fileContent.Length
-          $header = "blob $fileSize`0"
-          $headerBytes = [System.Text.Encoding]::UTF8.GetBytes($header)
-          $combinedBytes = $headerBytes + $fileContent
-          $sha1 = [System.Security.Cryptography.SHA1]::Create()
-          $hashBytes = $sha1.ComputeHash($combinedBytes)
-          $hexHash = ($hashBytes | ForEach-Object { $_.ToString("x2") }) -join ""
-          return $hexHash.Substring(0, 7)
+        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
+        # Verify files exist before renaming
+        if (Test-Path "${{ github.workspace }}\x64\Nightly\LatiteRewrite.dll") {
+          Rename-Item -Path "${{ github.workspace }}\x64\Nightly\LatiteRewrite.dll" -NewName "LatiteNightly.dll"
+        } else {
+          Write-Error "LatiteRewrite.dll not found in Nightly build output"
+          exit 1
         }
-        $hash = Get-GitStyleSha1 -FilePath "LatiteRewrite.dll"
-        echo "sha1=$hash" >> $env:GITHUB_OUTPUT
 
     - name: Create GitHub Release
       uses: softprops/action-gh-release@v2.3.2
       with:
-        tag_name: ${{ steps.sha1.outputs.sha1 }}
-        name: Latite Nightly ${{ steps.sha1.outputs.sha1 }}
+        tag_name: nightly
+        name: Latite Nightly
         body: |
           ### This is an automated, experimental DLL build of Latite Client.
           
           **This release has a high chance of containing bugs or crashes.**
         prerelease: true
-        files: ${{ github.workspace }}/x64/Nightly/LatiteRewrite.dll
+        files: ${{ github.workspace }}/x64/Nightly/LatiteNightly.dll
